# Generated by Django 2.0.4 on 2018-04-19 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='')),
                ('title', models.CharField(default=None, max_length=20)),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(default='OK', max_length=30)),
            ],
        ),
    ]
