# Generated by Django 2.0.4 on 2018-04-27 15:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('state', models.CharField(default='OK', max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='unknown', max_length=25)),
                ('datetime', models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 27, 17, 23, 25, 148751))),
                ('document', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=20)),
            ],
        ),
    ]
