# Generated by Django 2.0.4 on 2018-04-16 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2018, 4, 16, 11, 7, 28, 401766)),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='document',
            name='state',
            field=models.CharField(default='OK', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=''),
        ),
    ]
