# Generated by Django 2.0.4 on 2018-04-27 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 4, 27, 17, 30, 24, 644380)),
        ),
    ]
