# Generated by Django 2.0.4 on 2018-04-16 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_auto_20180416_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2018, 4, 16, 11, 42, 14, 25770)),
        ),
    ]
