# Generated by Django 2.0.4 on 2018-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_auto_20180427_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
