# Generated by Django 2.0.4 on 2018-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_auto_20180419_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extension',
        ),
    ]
