# Generated by Django 2.0.4 on 2018-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0003_remove_document_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=25, null=True),
        ),
    ]
