# Generated by Django 2.0.4 on 2018-04-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0003_auto_20180416_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='state',
        ),
    ]
